site_title: Sunny Draws
site_tagline: Free illustration PNG download


plugins:
  - jekyll-paginate-v2

collections:
  illustrations:
    output: true
    permalink: /illustrations/:name/
    #permalink: /illustrations/:categories/:name/


# 分頁插件設定(使用 jekyll-paginate-v2 插件）
pagination:
  enabled: true
  collections:
    illustrations:
      permalink: '/illustrations/page/:num/' # 這是「總覽分頁」的網址
  sort_field: 'date'
  sort_reverse: true
  per_page: 18


autopages:
  enabled: true

  collections:
    enabled: false   # ❗ 一定要這行

  tags:
    enabled: false   # ❗ 一定要這行

  categories:
    enabled: true
    collections:
      - illustrations   # 👈🔥 這行是關鍵
    layouts:
      - 'illustration-category.html'
    title: 'Posts in category :cat'
    permalink: '/illustrations/:cat/'

  pagination:   # 👈🔥🔥🔥 加這段
      enabled: true
      per_page: 18